### ISSUE TITLE
Strange blank history items without visible content

### ISSUE THREAD

**Issue by Emulator000** [hluk/CopyQ#1728]
**Describe the bug**
When I open the main history window, I can't see selectable items as expected

**To Reproduce**
1. Go to 'CopyQ main window

**Expected behavior**
Items listed as expected

**Screenshots**
![image](https://user-images.githubusercontent.com/15048541/128614187-48b3b1ab-f011-4131-92c0-e3be7492438b.png)

**Version, OS and Environment**
CopyQ Clipboard Manager v4.1.0~focal
Qt: 5.12.8
KNotifications: 5.68.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 20.04.2 LTS

**Additional context**
I tried to see the Log window in order to check if there are some errors but I can't find anyting significant, screenshot here: 
![image](https://user-images.githubusercontent.com/15048541/128614228-464d92e8-97cf-435c-9f52-8777d74c565c.png)

Also, when I go into the Appearance window, CopyQ crashes after few seconds, I tried to set another theme manually without luck.

**Comment by hluk** [comment]
Can you share backtrace if possible? It might be possible with `coredumpctl info copyq`.

**Comment by Emulator000** [comment]
@hluk unfortunately no coredumps, here what I receive:
```sh
$ coredumpctl info copyq
No coredumps found.
```

Also, the first time I opened CopyQ when I rebooted the system, I saw the Apparence window with not selectable items and empty list for fonts etc 😢

**Comment by hluk** [comment]
That looks like something is wrong with Qt libraries or system theme.

Maybe updating system packages would help. Where did you install CopyQ from?

**Comment by Emulator000** [comment]
@hluk packages all updated, do you have any hint to set default values for Qt, I never touched but maybe the issue is there...

I installed CopyQ from your PPA

**Comment by hluk** [comment]
Can you try installing CopyQ from flatpak instead? See: https://copyq.readthedocs.io/en/latest/installation.html

**Comment by Emulator000** [comment]
@hluk sorry for the delay, is the same thing unfortunately...

**Comment by hluk** [comment]
That's interesting, the Flatpak should use different Qt libraries and clean configuration, so I would assume that the result would be different.

Can you check the debug logs when you launch the app with the following command?

```bash
env COPYQ_LOG_LEVEL=DEBUG copyq
```

**Comment by LubosRemplik** [comment]
Not sure what happend, but cant say this is happening to me any more. No update of copyQ as far as I know and it is working...

Only change which might be related is I have uninstalled https://micheleg.github.io/dash-to-dock/ gnome extension.

So maybe some conflict or this dash to dock gnome extension is doing something nasty...

**Comment by LubosRemplik** [comment]
> Not sure what happend, but cant say this is happening to me any more. No update of copyQ as far as I know and it is working...
> 
> Only change which might be related is I have uninstalled https://micheleg.github.io/dash-to-dock/ gnome extension.
> 
> So maybe some conflict or this dash to dock gnome extension is doing something nasty...

Yep, exaclty as I said... same as version as per #1861 

```
CopyQ Clipboard Manager 5.0.0-115-gf9c668f7
Qt: 5.15.2
KNotifications: 5.86.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Ubuntu 21.10
```

**Comment by freeo** [comment]
I witnessed the same today and have some further input:

- first time I started CopyQ in session of the installation it worked just fine!
- Next day after reboot: same as in the screenshot above (intesting though: I can go up/down in the list, it select properly and pasting works as expected, but since I can't see what I'm selecting... it's of no use)
- Tested if my window manager is at fault (awesomewm): CopyQ worked as expected in Gnome based Pop OS desktop env (no dash to dock was used)
- XFCE: didn't work, same issue as with plain awesomewm

Any outputs wanted to help debug?

**Comment by hluk** [comment]
Can you provide debug logs and a crash report (stacktrace)? This is probably some issue with conflicting libraries/plugins in Ubuntu.

**Comment by LubosRemplik** [comment]
Urgh, it was good for some time but now it is back... I guess it has something to do with my graphic driver and gnome. It was good for while on fresh start, when I do "play" with my monitor setup there is same issue again

**Comment by LubosRemplik** [comment]
And now it is working, I am having legion 5 pro with nvidia graphic and this laptop has modes, when I am on mode which is definately using nvidia driver then this issue happens, when on normal mode and freshly booted system then it works

**Comment by Emulator000** [comment]
Stil not working, fresh installed machine with Pop_OS! and Nvidia drivers, same issue happens

**Comment by NC-VZLA** [comment]
Hi, I've been having the same issue, It used to work fine until the last couple of updates, I tried uninstalling it, purge it, manually removing the config folders, but to no avail.

```
OS: KDE neon User - 5.25 x86_64 
Host: ZBOX-EN1070/1060,EN1070K/1060K XX 
Kernel: 5.18.10-76051810-generic 
Packages: 2559 (dpkg), 34 (flatpak), 12 (snap) 
Shell: fish 3.5.1 
Resolution: 5120x1440, 3840x2160 
DE: Plasma 
WM: KWin 
WM Theme: Breeze 
Theme: Breeze Dark [Plasma], Breeze [GTK2/3] 
Icons: breeze-dark [Plasma], breeze-dark [GTK2/3] 
Terminal: yakuake 
CPU: Intel i5-7500T (4) @ 2.700GHz 
GPU: NVIDIA GeForce GTX 1070 Mobile 
GPU: Intel HD Graphics 630 
Memory: 7208MiB / 32033MiB 
```
``
[CopyQ_Log.txt](https://github.com/hluk/CopyQ/files/9276337/CopyQ_Log.txt)

**Comment by hluk** [comment]
@NC-VZLA Did you try this with the latest version (6.2.0)?

**Comment by NC-VZLA** [comment]
Yes, the log was when I just reinstalled 6.2.0~focal

**Comment by hluk** [comment]
:bulb: Another idea: The app style sheet can sometimes conflict with the system theme. So one thing to try is to **avoid setting any style sheet** to the item list.

1. Exit CopyQ.
2. Open `~/.config/copyq/copyq.conf` in an editor.
3. Change `css_template_items=items` option (or add it if it is missing):
```ini
[Theme]
css_template_items=
```
4. Save the changes.
5. Start CopyQ.

**Comment by NC-VZLA** [comment]
Just Updated to 6.3.0, and it fixed the main window issues, but the appearance menu in the preferences is still misbehaving, after being selected takes at least 40 seconds to load and the middle section (where you select the appearance) is still blown out of proportion. I didn't try to change the appearance,

**Comment by hluk** [comment]
> the appearance menu in the preferences is still misbehaving, after being selected takes at least 40 seconds to load and the middle section (where you select the appearance) is still blown out of proportion

I think it has something to do with the optimized [item rendering/loading code](https://github.com/hluk/CopyQ/blob/60f053e1c498a2f5ff82d034e9b3c7b2fcf025da/src/gui/clipboardbrowser.cpp#L1064-L1093). It is possible that the `preload()` call triggers another refresh recursively.

**Comment by hluk** [comment]
I'm trying to simplify and improve the rendering and item preloading some more.

If you can, **please help test** the new development flatpak image: https://github.com/flathub/com.github.hluk.copyq/pull/44 (scroll to the latest flathubbot comment and use the command to install the flatpak)

Specifics to **tests**:
- items are rendered in the list correctly
- list can be scrolled properly with mouse wheel and scrollbar
- keyboard item browsing is stable (up/down arrows, page up/down, end/home)
- Appearance tab in Preferences works properly

**Comment by Emulator000** [comment]
thank you so much @hluk for this! I finally see the ListView correctly on every machine I have! 😄

**Comment by hluk** [comment]
I've completely rewritten the rendering code. Please help testing it.

For Linux, there is a Flatpak image you can install using the latest instructions from flathubbot: https://github.com/flathub/com.github.hluk.copyq/pull/44#issuecomment-1255259412

Test build for Windows: https://ci.appveyor.com/project/hluk/copyq/builds/44855887/artifacts

**Comment by richlux** [comment]
This latest build appears to be working well for me on Windows 10

Rich

**Comment by FreeHarry** [comment]
> I've completely rewritten the rendering code. Please help testing it.
> 
> For Linux, there is a Flatpak image you can install using the latest instructions from flathubbot: [flathub/com.github.hluk.copyq#44 (comment)](https://github.com/flathub/com.github.hluk.copyq/pull/44#issuecomment-1255259412)
> 
> Test build for Windows: https://ci.appveyor.com/project/hluk/copyq/builds/44855887/artifacts

Tested on Windows 10. It seems problem with big, blank boxes is solved. But there is another one now: If I copy a string which is already existing in the CopyQ history, then this item is not show as selected/visible after I open the CopyQ window.

**Comment by hluk** [comment]
Thanks for testing!

> If I copy a string which is already existing in the CopyQ history, then this item is not show as selected/visible after I open the CopyQ window.

@FreeHarry Do you mean there is an empty item (blank box) at the top? Can you share a screenshot?

**Comment by hluk** [comment]
I have added more update-item-list calls on couple of events (for example for item data change) to ensure the item list stays updated.

New build for Windows: https://ci.appveyor.com/project/hluk/copyq/builds/44861458/artifacts

**Comment by hluk** [comment]
I did another round of fixing and refactoring. The rendering and scrolling should now be much more stable and faster.

Linux Flatpak image (install using the latest instructions from flathubbot): https://github.com/flathub/com.github.hluk.copyq/pull/44#issuecomment-1256890960

Windows build: https://ci.appveyor.com/project/hluk/copyq/builds/44870425/artifacts

**Comment by hluk** [comment]
I have released the fixes in the new 6.3.1 version.

**Comment by NC-VZLA** [comment]
Just installed 6.3.1 All looks great as of now. Thanks for your hard work. If I see anything, I'll update the ticket, but as of this moment looks like the bug is solved on Linux at least.

**Comment by Emulator000** [comment]
@hluk the main List issue is now officially resolved, congrats 🎉 

One more issue remain though, look here on the Appearance settings:
![image](https://user-images.githubusercontent.com/15048541/193451309-6fd724fd-b930-4dbb-b99f-128efc6875bc.png)

While you click the specific settings section CPU goes 100% and the thread is stuck for some seconds, then everything is messed up and you can't actually change anything 😢

**Comment by Chealer** [comment]
@Emulator000: Does that persist? If so, please file a new ticket specifically about that, indicating your version, and mark this one as resolved.

**Comment by Ardemus** [comment]
I'm seeing this issue at day 17/18 in the copyq instance I'm running for issue #3247.

My System:

> CopyQ V13 native from your PPA
> Linux Mint 23.3
> 6.14.0-37-generic kernel
> Cinnamon 6.6.7
> X11
> AMD RX 580 graphics
> 16 GB RAM
> QT - I still don't know how to tell
 
I generally don't use the copyq ui, so this problem may come and go? In the past the UI has worked fine every time I've tried it on every version I used while testing #3247.

I used the UI a few times early on in this run of copyq when I was copying large spreadsheet data to investigate what it displayed and it worked fine.

I had been making a large daily copy of spreadsheet data until the 27th when I started to copy large raster images from gimp. On the 28th I noticed that a 2nd copy of the same image didn't increase copyq memory use and I checked the UI to find that it had moved the image to the top of the history instead of making a new entry (a good design decision). The UI was fine.

I then tried a different image, found that memory use still didn't tick up, and checked the UI again. That was when the UI came up blank.

It looked like the following screenshot, but with the toolbar on the right missing and an empty rectangle in it's place (I don't remember what color the empty rectangle was, but it has been black since). It has continued to be broken for the last 24 hours, though sometimes it shows the toolbar and sometimes it shows the black rectangle.

<img width="970" height="865" alt="Image" src="https://github.com/user-attachments/assets/26d5f2c6-8215-4861-b072-509224b398d9" />

Just before writing this I copied another large raster image, noted that the window was still blank, and did a little investigation:

* Right clicking on the task bar icon does show a list of recent copies like normal.
* Item > Show Content shows the contents of the most recent copy
* Clicking, double clicking, and right clicking on the blank area does not seem to do anything
* **The size of the .dat files dropped off dramatically** shortly after I first saw the blank copyq window (from 189,414 kB in 92 files to 72,878 kB in 38 files about 4 minutes after I opened the blank window, according to the logs that I keep for #3247). The new dat file count and size has remained almost exactly the same for the past 24 hours.
* Memory use did not change
* Calling `coredumpctl info copyq` in a terminal returns `No coredumps found`
* There is nothing suspicious in the application logs: [copyq_20260429.log](https://github.com/user-attachments/files/27216662/copyq_20260429.log)


Then I clicked on File > New Item and some things changed:

<img width="970" height="1244" alt="Image" src="https://github.com/user-attachments/assets/048b3cbf-7c62-4919-86e0-86bbab389ba0" />

* File > Show Clipboard Content still shows the last item copied (not an empty item)
* Note that the toolbar is now missing
* The Item menu is now empty (there is no visible change when I attempt to pull it down)
* Right clicking on the task bar icon the list of recent copies does now have a blank entry at the top

## Going Forward
I fully expect that the UI will return to normal when I restart the app. I will leave this instance running for now in case you want me to do anything else.

**Comment by Chealer** [comment]
Thank you for reporting @Ardemus, but I do not see any indication that the issue tracked here would be intermittent. If your issue persists in CopyQ 15 or above, I suggest checking whether your issue better matches issue #2511.

[🅭🄍](https://www.philippecloutier.com/Common+infrastructure+licensing#its)

**Comment by Ardemus** [comment]
@Chealer

Hello, I'm happy to help.

> If your issue persists in CopyQ 15 or above, I suggest checking whether your issue better matches issue https://github.com/hluk/CopyQ/issues/2511.

Sure, #2511 does seem like the same behavior, but intermittent. I can switch to v15 once the Ubuntu PPA gets updated. Do you have any idea if/when that will happen so I can keep an eye out for it? I'd use the flatpak, but that's been an entirely different beast in my #3247 tests, so I'd hate to add those variables.

Incidentally, restarting V13 native did restore the UI. Copyq seems to have worked just fine in the background and the expected copy history is there.

**Comment by Chealer** [comment]
Greetings @Ardemus,

> I can switch to v15 once the Ubuntu PPA gets updated. Do you have any idea if/when that will happen so I can keep an eye out for it? I'd use the flatpak, but that's been an entirely different beast in my [#3247](https://github.com/hluk/CopyQ/issues/3247) tests, so I'd hate to add those variables.

I understand your hesitation, but I have no idea of when Debian packages will be available. If you can't wait, perhaps AppImage (an alpha is mentioned in ticket #3420) is an option.

> Incidentally, restarting V13 native did restore the UI. Copyq seems to have worked just fine in the background and the expected copy history is there.

Thanks
