### ISSUE TITLE
Increase font size of command/script text editor

### ISSUE THREAD

**Issue by reagle** [hluk/CopyQ#1757]
Running CopyQ 4.1.0 on macOS 11.6 20G165 arm64. How do I change/increase the font size in the script text editor?

I've toyed with all the settings in /Settings/Appearance but they seem to have no effect.

<img width="537" alt="Screen Shot 2021-09-16 at 15 17 49" src="https://user-images.githubusercontent.com/596814/133672354-36e1baa0-b309-4c6a-b608-c4061fd1f2f0.png">

**Comment by reagle** [comment]
BTW: That screenshot was from an earlier version, but I am running v4.1.0-g2f223292-v4.1.0 now and confirm this is an issues.

**Comment by hluk** [comment]
Hmm, I think the editor is using default monospace font: https://github.com/hluk/CopyQ/blob/cbefe1c9124d805eb0bd9cda41ede285c1b1d07f/src/gui/commandedit.cpp#L81-L82

I think the `QFont::TypeWriter` style hint might not be correct - it should use `QFont::Monospace` instead.

**Comment by hluk** [comment]
Can you verify that the font looks better in [this development version](https://github.com/hluk/CopyQ/actions/runs/1253473238#artifacts)?

**Comment by reagle** [comment]
Yes, it's now a monospace font. But it's still too small and I can't change the size in /Preferences/Appearance/Editor.

<img width="326" alt="Screen Shot 2021-09-20 at 12 57 39" src="https://user-images.githubusercontent.com/596814/134043034-65139f24-9ced-4a20-8a35-0471d0661160.png">

**Comment by hluk** [comment]
> Rather, I can change/edit that configuration, but it has no effect on the command edit window.

Done. It should be implemented in [this dev build](https://github.com/hluk/CopyQ/actions/runs/1257111047#artifacts).

**Comment by reagle** [comment]
The command edit window is certainly more readable than when I started this issue, but I still don't think it's paying attention to the appearance settings. If I change them to obvious/extreme differences, it still looks the same.

<img width="1330" alt="Screen Shot 2021-09-21 at 08 02 19" src="https://user-images.githubusercontent.com/596814/134167129-22d2f928-aeac-4fce-9abc-f8c22f115b23.png">

**Comment by hluk** [comment]
Hmm, looks like there is a bug requiring the configuration to be applied twice.

**Comment by reagle** [comment]
I think I hit the okay, then apply, then okay, and quit and restarted...?

**Comment by reagle** [comment]
Actually, I just went into commands again and the fonts are larger. Whatever it is, there's certainly a lag between applying and seeing.

**Comment by hluk** [comment]
The configuration updates are fixed in [this build](https://github.com/hluk/CopyQ/actions/runs/1257881378#artifacts) - the font should be reloaded right after you click OK/Apply in the Preferences.

**Comment by reagle** [comment]
Confirmed! Thank you.
