### ISSUE TITLE
Ubuntu 14.04: Unable to show main window after autostart ("X Error of failed request: BadWindow")

### ISSUE THREAD

**Issue by kroogar** [hluk/CopyQ#392]
When selecting "Autostart" from Preferences CopyQ isn't started properly. There's no icon in the top panel and it's not responding to "copyq toggle". Doing a ps aux | grep copyq returns this:

me     5699  0.1  0.5 4213424 91600 ?       Sl   18:50   0:01 copyq
me     5711  0.0  0.2 733916 33916 ?        Sl   18:50   0:00 /usr/bin/copyq monitor /home/me/.config/copyq/.copyq_m
me     6516  0.0  0.0  15948  2200 pts/0    S+   19:11   0:00 grep --color=auto copyq

then I do a killall copyq and start it from Unity Dash and it works flawlessly.

The command in the Startup app is

"usr/bin/copyq"

Anyone got a hint as to what might be happening?

**Comment by hluk** [comment]
What does `copyq toggle` print when the app doesn't respond?

**Comment by nirmalksamuel** [comment]
I have similar problem in OS X  10.9.5. I described it elsewhere.  I suspect this may not be related to OS versions, but a generic problem.

**Comment by kroogar** [comment]
'copyq toggle' returns

X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  3 (X_GetWindowAttributes)
  Resource id in failed request:  0x180000f
  Serial number of failed request:  8
  Current serial number in output stream:  9

**Comment by kroogar** [comment]
Also I've noticed that unchecking the Autostart option in Preferences will *not* remove CopyQ from Startup. Dunno if makes any difference :-)

**Comment by jagandecapri** [comment]
Having the same problem in Ubuntu 14.04.

`copyq show` output:
> X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  3 (X_GetWindowAttributes)
  Resource id in failed request:  0x2600004
  Serial number of failed request:  8
  Current serial number in output stream:  9

**Comment by hluk** [comment]
Everything works fine for me on Ubuntu 14.04.

Can you try opening the window with following command?

    copyq showAt 0 0 500 500

(BTW, I fixed the autostart issue - Ubuntu uses different option in autostart files.)

**Comment by kroogar** [comment]
`copyq showAt 0 0 500 500`

Works just fine. Displays the window in the upper left corner.

**Comment by kroogar** [comment]
Autostart still doesn't work for me on Ubuntu 14.04. Is there an update I should download?

**Comment by hluk** [comment]
Seems that saved window geometry is wrong and Qt and window manager fail to fix that. Try to move/resize the window, after restart it should be opened with same geometry.

I'll try to add some code to ensure the whole window is visible on screen.

Autostart will be fixed in next release, for now you have to use Ubuntu configuration (build the app from git).

**Comment by jagandecapri** [comment]
I am using CopyQ Clipboard Manager v2.4.9

`copyq showAt 0 0 500 500`
shows this error for me
`CopyQ client ERROR: Name "showAt" doesn't refer to a function.`

**Comment by hluk** [comment]
Are you sure you are running 2.4.9 version? Check version in About dialog [F1] in GUI.

**Comment by jagandecapri** [comment]
Yes. It is 2.4.9. Anyway, I rebooted by computer and got CopyQ working. I killed the current running CopyQ process and started it again. It seems to be working.

**Comment by kroogar** [comment]
Unfortunately Autostart isn't working in 2.5.0 on Ubuntu 14.04 LTS :-(

**Comment by hluk** [comment]
Does that mean that the application is not started or you just cannot display main window?

What is the output of following commands?

```
copyq toggle
copyq showAt 0 0 500 500
```

**Comment by kroogar** [comment]
me@ubuntu:~$ copyq toggle
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  3 (X_GetWindowAttributes)
  Resource id in failed request:  0x1a0000f
  Serial number of failed request:  8
  Current serial number in output stream:  9
me@ubuntu:~$ copyq showAt 0 0 500 500
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  3 (X_GetWindowAttributes)
  Resource id in failed request:  0x1a0000f
  Serial number of failed request:  8
  Current serial number in output stream:  9

**Comment by hluk** [comment]
Last time you [mentioned](https://github.com/hluk/CopyQ/issues/392#issuecomment-148897221) that the second command worked. This seems like an issue in window manager. Perhaps adding interval before launch to `$HOME/.config/autostart/copyq.desktop` will help. I.e. change line

     Exec=copyq

to

    Exec=sh -c "sleep 5; copyq"

**Comment by hluk** [comment]
This could be actually [Qt bug](https://bugreports.qt.io/browse/QTBUG-1782).

**Comment by kroogar** [comment]
Adding a 5 sec sleep didn't help :-(

I wouldn't about the Qt bug. I don't do Linux programming (yet :-) )

**Comment by edevil** [comment]
I'm running Ubuntu 17.10 and also have problems with the autostart, there's no "copyq" process running after I login. How does copyq configure itself for this behaviour?

```
➜  ~ copyq version
CopyQ Clipboard Manager v3.3.0 (hluk@email.cz)
Built with: Qt 5.9.1, LibQxt 0.7.0
➜  ~ copyq toggle 
ERROR: Cannot connect to server! Start CopyQ server first.
```

**Comment by hluk** [comment]
@edevil Did you enable "Autostart" option in "General" config tab?

**Comment by edevil** [comment]
@hluk yes, I did.

**Comment by hluk** [comment]
@edevil What does following command print?

```bash
grep 'Exec\|Hidden' ~/.config/autostart/copyq.desktop
```

**Comment by edevil** [comment]
Even though I select "Autostart" that file is never created. Also, when I restart CopyQ the Autostart option is always off.

**Comment by hluk** [comment]
The original issue seems to be `X Error of failed request: BadWindow` error when trying to show main window (`copyq toggle`) after autostart.

New version of CopyQ uses Qt 5. So this may not be an issue anymore. If it is, please reopen.

@edevil Seems like your issue is different. Can you open another issue? Thanks.
