### ISSUE TITLE
Selection of item in tray does not paste it to current window

### ISSUE THREAD

**Issue by MortenZdk** [hluk/CopyQ#439]
Opening tray box and selecting an item does not past this to the current windows, even though using preference Configuration => Tray => Paste activated item to current windows as ticked.

? I am misunderstanding this feature, or is it a issue with CopyQ ?

Setup: Using ver. 2.5.0, Windows 7, 64-bit.

**Comment by hluk** [comment]
I'm aware that this may not work in some application. Which application did you try to paste to?

**Comment by MortenZdk** [comment]
Does not work to MS Notepad, for example.

**Comment by hluk** [comment]
Do you open the tray menu with a shortcut?

It doesn't seem to work (tested on Windows 8) if the menu is opened by clicking on tray icon. I would need to get previously focused window somehow because the panel seems to get focus before the menu is opened (BTW the code is [here](https://github.com/hluk/CopyQ/blob/07501613f7950ba7d0d932acf35b7636b1e6f03b/src/platform/win/winplatform.cpp#L168)).

**Comment by MortenZdk** [comment]
Yes, I open the tray with a shortcut (Ctrl-Shift-V), and focus is returned to the previous window when I click or select a tray item, and the item is place in the clip board, but it is just not pasted to the active window.

**Comment by HarelM** [comment]
+1, I'm looking for a better alternative to ClipX which can currently do it...

**Comment by hluk** [comment]
This is already implemented (though there are still issues when opening the tray menu by mouse). I'm still failing to reproduce this issue -- pasting from tray menu when opened with shortcut works for me on Windows 7, 8 and 10.

@MortenZdk Did you try latest version? Are there any other application that may break the behavior (special windows theme or windows management tool running)?

**Comment by HarelM** [comment]
Is there a way to activate debug logs and attach it? I can easily reproduce it.

**Comment by MortenZdk** [comment]
Just turned off all my other windows management utilities, and retried, 
but with same result.  I am also opening the tray menu with a shortcut.

Please let me know how I can help with debugging this issue.

/MortenZdk

**Comment by MortenZdk** [comment]
I just tried pasting from the tray menu with a shortcut on another computer, and that worked find, even through I have basically the same background programs running.  Using Win 7 64-bits on both.

**Comment by hluk** [comment]
I did some fixes for pasting from tray. Hopefully this problem will be also resolved in next version.

**Comment by HarelM** [comment]
I installed the app on another computer and this still doesn't work for me. Used the latest released version.
Steps to reproduce:
1. Install the app.
2. Go to preferences, shortcuts, Custom action and global shortcuts and added show/hide main  window with Ctrl+Shift+V
3. Copy a few items
4. Go to chrome address bar and clicked Ctrl+Shift+V in order to paste an item
5. Click down arrow to get to one of the items
6. Clicked enter to paste
Nothing happens.
When clicking Ctrl-V the right item is pasted, but this is not the expected behavior I guess...

**Comment by HarelM** [comment]
I think I know what the issue was:
I did the following and now everything is working:
1. Go to Preferences, History
2. Check **Focus last window** and **Paste to current window**.
I'm not sure why these are not on by default though...

**Comment by forteller** [comment]
I was hoping Focus last window would let me paste into tweetdeck.twitter.com, but no such luck. I can paste from the CopyQ window into most applications and places, including Firefox. But not into Tweetdeck in Firefox, for some reason. If it would be possible to fix that I would be very grateful.

**Comment by hluk** [comment]
Pasting to applications on Windows has been improved in CopyQ v2.7.0.

Firefox pasting issue is in #505 (it's bit unrelated to this task since an element on web page needs to get focus).

**Comment by MortenZdk** [comment]
Great, now it works using 2.7.0 :-)
Just tried pasting to Notepad.
Have a nice weekend.

**Comment by hadavand** [comment]
> I installed the app on another computer and this still doesn't work for me. Used the latest released version.
> Steps to reproduce:
> 
> 1. Install the app.
> 2. Go to preferences, shortcuts, Custom action and global shortcuts and added show/hide main  window with Ctrl+Shift+V
> 3. Copy a few items
> 4. Go to chrome address bar and clicked Ctrl+Shift+V in order to paste an item
> 5. Click down arrow to get to one of the items
> 6. Clicked enter to paste
>    Nothing happens.
>    When clicking Ctrl-V the right item is pasted, but this is not the expected behavior I guess...

I have the same problem, but when I open text editors (sublime text, gedit, ...etc) with root user by typing sudo before theme,  **copyq** works properly and the _step 6_ that @HarelM mentioned works as I expected.
