### ISSUE TITLE
bug: shortcuts not saved after restarting the app

### ISSUE THREAD

**Issue by royharoush** [hluk/CopyQ#482]
Hi, 
it looks like saving shortcuts under the shortcuts menu does not persist after closing and opening copq. 
i've tried assigning ctrl+e and ctrl+w to different functions then there default settings, i've removed the original actions, and assigned the new actions, closed the program, and the default settings were set again, in addition to what i've (so i have a conflict and none of the functions work untill i remove the conflicts). 

copyq is 2.6.1, both windows and debian.
i've looked all over copyq*ini but i couldnt find this configuration anywhere(thought maybe i'd change it in a configuration file, but i can only see my global shortcut for toggling the app). 

let me know if you need more information. 

thanks 
roy

**Comment by hluk** [comment]
Fixed. Thanks for the report!

I think you must be using some version compiled from git repo (2.6.1-something).

**Comment by royharoush** [comment]
Hi,
I've downloaded the automagically compiled version for windows from 
https://ci.appveyor.com/project/hluk/copyq/build/artifacts

this issue is not resolved :|

do i need to compile from git source to have this fix ? 
I need to compile for windows. 
Thanks,
Roy

**Comment by hluk** [comment]
Can you post application version (from About dialog <kbd>F1</kbd>)? Also check if there are no errors/warnings with <kdb>F12</kdb>.

**Comment by royharoush** [comment]
Clipboard Manager v2.6.1-75-g07012d9

error log:

C:/Users/user/AppData/Roaming/copyq/copyq/copyq.log

Warning [2016-04-04 14:15:55.085]: CopyQ server is already running.
Note [2016-04-04 14:17:25.166]: Loading plugin: C:/Users/user/Downloads/copyq/plugins/itemdata.dll
Note [2016-04-04 14:17:25.175]: Loading plugin: C:/Users/user/Downloads/copyq/plugins/itemencrypted.dll
Note [2016-04-04 14:17:25.183]: Loading plugin: C:/Users/user/Downloads/copyq/plugins/itemfakevim.dll
Note [2016-04-04 14:17:25.190]: Loading plugin: C:/Users/user/Downloads/copyq/plugins/itemimage.dll
Note [2016-04-04 14:17:25.197]: Loading plugin: C:/Users/user/Downloads/copyq/plugins/itemnotes.dll
Note [2016-04-04 14:17:25.204]: Loading plugin: C:/Users/user/Downloads/copyq/plugins/itemsync.dll
Note [2016-04-04 14:17:25.211]: Loading plugin: C:/Users/user/Downloads/copyq/plugins/itemtags.dll
Note [2016-04-04 14:17:25.218]: Loading plugin: C:/Users/user/Downloads/copyq/plugins/itemtext.dll
Note [2016-04-04 14:17:25.257]: Loading plugin: C:/Users/user/Downloads/copyq/plugins/itemweb.dll
ERROR [2016-04-04 14:18:02.185]: QWindowsPipeReader::completeAsyncRead: Unknown error 995
Note [2016-04-04 14:18:50.003]: Loading plugin: C:/Users/user/Downloads/copyq/plugins/itemdata.dll
Note [2016-04-04 14:18:50.037]: Loading plugin: C:/Users/user/Downloads/copyq/plugins/itemencrypted.dll
Note [2016-04-04 14:18:50.079]: Loading plugin: C:/Users/user/Downloads/copyq/plugins/itemfakevim.dll
Note [2016-04-04 14:18:50.121]: Loading plugin: C:/Users/user/Downloads/copyq/plugins/itemimage.dll
Note [2016-04-04 14:18:50.160]: Loading plugin: C:/Users/user/Downloads/copyq/plugins/itemnotes.dll
Note [2016-04-04 14:18:50.207]: Loading plugin: C:/Users/user/Downloads/copyq/plugins/itemsync.dll
Note [2016-04-04 14:18:50.249]: Loading plugin: C:/Users/user/Downloads/copyq/plugins/itemtags.dll
Note [2016-04-04 14:18:50.287]: Loading plugin: C:/Users/user/Downloads/copyq/plugins/itemtext.dll
Note [2016-04-04 14:18:50.660]: Loading plugin: C:/Users/user/Downloads/copyq/plugins/itemweb.dll
Note [2016-04-04 14:22:52.408]: Loading plugin: C:/Users/user/Downloads/copyq/plugins/itemdata.dll
Note [2016-04-04 14:22:52.416]: Loading plugin: C:/Users/user/Downloads/copyq/plugins/itemencrypted.dll
Note [2016-04-04 14:22:52.422]: Loading plugin: C:/Users/user/Downloads/copyq/plugins/itemfakevim.dll
Note [2016-04-04 14:22:52.428]: Loading plugin: C:/Users/user/Downloads/copyq/plugins/itemimage.dll
Note [2016-04-04 14:22:52.435]: Loading plugin: C:/Users/user/Downloads/copyq/plugins/itemnotes.dll
Note [2016-04-04 14:22:52.442]: Loading plugin: C:/Users/user/Downloads/copyq/plugins/itemsync.dll
Note [2016-04-04 14:22:52.448]: Loading plugin: C:/Users/user/Downloads/copyq/plugins/itemtags.dll
Note [2016-04-04 14:22:52.455]: Loading plugin: C:/Users/user/Downloads/copyq/plugins/itemtext.dll
Note [2016-04-04 14:22:52.500]: Loading plugin: C:/Users/user/Downloads/copyq/plugins/itemweb.dll
ERROR [2016-04-04 14:23:44.325]: QWindowsPipeReader::completeAsyncRead: Unknown error 995
Warning [2016-04-09 18:00:08.760]: CopyQ server is already running.
Note [2016-04-09 18:01:35.768]: Loading plugin: C:/user/copyq/plugins/itemdata.dll
Note [2016-04-09 18:01:35.820]: Loading plugin: C:/user/copyq/plugins/itemencrypted.dll
Note [2016-04-09 18:01:35.869]: Loading plugin: C:/user/copyq/plugins/itemfakevim.dll
Note [2016-04-09 18:01:35.902]: Loading plugin: C:/user/copyq/plugins/itemimage.dll
Note [2016-04-09 18:01:35.941]: Loading plugin: C:/user/copyq/plugins/itemnotes.dll
Note [2016-04-09 18:01:35.980]: Loading plugin: C:/user/copyq/plugins/itemsync.dll
Note [2016-04-09 18:01:36.017]: Loading plugin: C:/user/copyq/plugins/itemtags.dll
Note [2016-04-09 18:01:36.054]: Loading plugin: C:/user/copyq/plugins/itemtext.dll
Note [2016-04-09 18:01:36.433]: Loading plugin: C:/user/copyq/plugins/itemweb.dll

**Comment by hluk** [comment]
I cannot reproduce this -- perhaps I'm testing something else.

Can you post some exact steps to reproduce the issue?

**Comment by royharoush** [comment]
1. try to edit\remove shortcut for the "toggle clipboard storing"
2. click on ok\apply. 
3. reopen the configuration panel. 
4. the default is back. 
![2016-04-10 00_29_01-greenshot](https://cloud.githubusercontent.com/assets/8113056/14406543/975e38ec-feb3-11e5-8f1e-b442c76838f0.png)
![wat](https://cloud.githubusercontent.com/assets/8113056/14406559/f917c3c8-feb3-11e5-8bed-a6f97fca6cb0.gif)

this also happens with "view content" default shortcuts, and "edit" shortcuts.

**Comment by hluk** [comment]
I fixed removing shortcuts (it's actually [Qt bug](https://bugreports.qt.io/browse/QTBUG-51237)).

But I still cannot reproduce the part where valid shortcuts are not saved.

Can you test again with [recent build](https://ci.appveyor.com/project/hluk/copyq/build/artifacts)?

**Comment by hluk** [comment]
Closing. Please reopen if it's still an issue.
