### ISSUE TITLE
Copying large images from Gimp crashes it.

### ISSUE THREAD

**Issue by Negirno** [hluk/CopyQ#636]
System: Ubuntu 16.04.2 LTS
CopyQ version: CopyQ Clipboard Manager v2.8.2 Built with: Qt 5.5.1, LibQxt 0.7.0 (downloaded from your repo)
Gimp version: 2.8.16 (the version available in the repositories)

Ever since I've installed this new version, when I copy something large to the clipboard, Gimp just exits, and the copied image doesn't appear in CopyQ.

Running it from the terminal gets me the following errors when copying:
```
The program 'gimp' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 23004 error_code 3 request_code 18 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

(script-fu:3913): LibGimpBase-WARNING **: script-fu: gimp_wire_read(): error
```
Interestingly, if I copy just a small part of the image, then this doesn't happen. It also didn't happen when I've tried to copy an empty image, although it does happen with very large ones (I tried 4096x4096 RGB color).

Edit: Forgot to mention it that this doesn't happen in Krita, even with large images (although it takes some time to appear in CopyQ)

**Comment by mutlay** [comment]
Yes, same issue, I had to uninstall CopyQ from 16.04 Ubuntu Gnome.

**Comment by hluk** [comment]
Looks like Gimp bug.

Strangely this doesn't happen when getting copied image data with `xclip`.

**Comment by hluk** [comment]
I wanted to debug this so I recompiled Gimp with debug symbols and I cannot reproduce this -- this is classic :(.

BTW, I'm using Arch Linux and Gimp 2.8.18. The version in from official package is affected with this bug.

**Comment by hluk** [comment]
Fixed. It seems it's partially an issue in Gimp and in Qt.

**Comment by rachmadaniHaryono** [comment]
@hulk it seem the bug is still exist

```console
The program 'gimp' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 263921 error_code 3 request_code 18 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

(script-fu:6014): LibGimpBase-WARNING **: 18:55:37.232: script-fu: gimp_wire_read(): error
```
- GNU Image Manipulation Program version 2.10.6
- copyq v3.7.0
- Linux q-X201EP 4.18.0-11-generic #12-Ubuntu SMP Tue Oct 23 19:22:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- ubuntu 18.10

**Comment by hluk** [comment]
@rachmadaniHaryono I tried my best to fix this but the fixes I've implemented makes the bug only happen less frequently.

It's bug in Gimp (or in some libs it uses) because it definitely should not cause a crash. And it's possibly a bug in Qt because of how it retrieves X11 clipboard/selection.

**Comment by rachmadaniHaryono** [comment]
which mean even if i use similar script like on #561 it will still crash?
```
[Command]
Automatic=true
Command="
    copyq ignore
    sleep 10
    copyq copy"
Icon=\xf084
Name=Ignore gimp
Remove=true
Window=.* - GIMP$
```

**Comment by Pastafarianist** [comment]
I'm getting a very similar crash with `shutter` (a screenshot tool written in Perl).

```
The program 'shutter' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 18205 error_code 3 request_code 18 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Comment by hluk** [comment]
Probably partially problem in how Qt retrieves data but I don't see how it can crash foreign app just by requesting clipboard unless there is a bug in that app itself (or in an library it uses, XCB, X11).

**Comment by Pastafarianist** [comment]
Shutter GUI is built on GTK. Not sure about Inkscape.

**Comment by sispus** [comment]
Using gtk3 fixes this issue for gimp 2.99. Former versions of gimp uses gtk2.

**Comment by louisgag** [comment]
I have the same issue with Gimp 2.10.18 on Ubuntu 20.04.1 LTS with copyq v3.10.0

I get the same message as @dniku but noting shows up in Xorg.0.log, even when running with --sync

**Comment by sispus** [comment]
Hi,
The issue is fixed in gimp with gtk3 (ver: 2.99). see: https://gitlab.gnome.org/GNOME/gimp/-/issues/789#note_844634 
You can switch to latest development package of gimp or wait for stable version, but they won't fix it for gtk2.

**Comment by louisgag** [comment]
Thanks. Upgrading gimp to beta works.
I had to first understand of to get the Flatpak system working, if anyone is wondering you need to run these two commands before doing the "[standard](http://ubuntuhandbook.org/index.php/2020/11/install-gimp-2-99-2-ubuntu-20-04/)" Flatpak gimp-beta installation.

`sudo flatpak --user remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo`
`flatpak install  org.gnome.Platform`

Too bad they won't fix it for all the other non-beta users.. I imagine there are a lot of people thinking that GIMP is unstable without knowing the bug comes from an incompatibility with CopyQ...

**Comment by hluk** [comment]
@sispus, @louisgag Thanks for posting the issue details and solution!

**Comment by Minipada** [comment]
Instructions for installing the beta: https://www.gimp.org/downloads/devel/

**Comment by danielkrajnik** [comment]
not sure if it's only about interaction with klipper, but on my kubuntu 20.04 both gimp 2.10 and 2.99 still fail to copy to clipboard and paste into chrome
