### ISSUE TITLE
Pasting from menu invoked from indicator focuses incorrect window (v2.9.0)

### ISSUE THREAD

**Issue by orschiro** [hluk/CopyQ#674]
Dear all, 

I am experiencing an occasional bug in the latest release. 

**Steps to reproduce:**

1. Click on the tray icon
2. Click on an entry in the listed menu to paste into the currently active (focused) window

**Expected result:**

Paste the content in the active window

**Occasional bug behaviour:**

The active window loses focus and focus is given to another window. The content of the clipboard is not pasted. 

Can someone reproduce this problem?

Yours,

Robert

**Comment by hluk** [comment]
Just tested it on Ubuntu. This is indeed problem in 2.9.0 but seems to be fixed in master branch.

**Comment by orschiro** [comment]
Thanks! The fix will thus become available in the next release?

**Comment by hluk** [comment]
@orschiro Yes. I hope to release new version soon.

**Comment by BjornMelgaard** [comment]
Also has this bug. On `copyq menu`, menu shows up near cursor and leaves focus on window under cursor after disappearing. Very irritating. 

```
# from i3 config
bindsym $mod+p       exec --no-startup-id "copyq menu"
```

**Comment by hluk** [comment]
@BjornMelgaard Interesting. This seems to be [intended behavior in i3](https://i3wm.org/docs/userguide.html#keybindings), it prevents focusing other windows until keys are released. To bypass this you can add `--release` argument so the command is run after keys are relased.

```
bindsym --release $mod+p       exec --no-startup-id "copyq menu"
```

You can also [map the shortcut in CopyQ](https://github.com/hluk/CopyQ/wiki/FAQ#13) instead.

**Comment by BjornMelgaard** [comment]
@hluk, Neither `--release` nor shortcut did not worked

**Comment by hluk** [comment]
@BjornMelgaard I was testing it with not-yet-released CopyQ (from master branch) on i3 4.13 (Arch Linux).

**Comment by BjornMelgaard** [comment]
[i3](https://youtu.be/u6WMt9qGD2s) , [copyq](https://youtu.be/owvGICtirqM)

```
$ copyq --version
CopyQ Clipboard Manager v2.9.0 (hluk@email.cz)
Built with: Qt 5.8.0, LibQxt 0.7.0
$ i3 --version
i3 version 4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors

```

**Comment by hluk** [comment]
@BjornMelgaard It's probably because of some changes in master branch. I'm just testing it so I can release it today (or hopefully really soon).

**Comment by BjornMelgaard** [comment]
Ok, looking forward to it)

**Comment by hluk** [comment]
@BjornMelgaard New version is [available](https://github.com/hluk/CopyQ/releases).

**Comment by BjornMelgaard** [comment]
@hluk , [no](https://youtu.be/3UCWDWdElms)

as you see, after tray is closed, the focus is following mouse
have tried with i3 shortcut - no

```
$ copyq --version
CopyQ Clipboard Manager v3.0.0 (hluk@email.cz)
Built with: Qt 5.8.0, LibQxt 0.7.0

```

**Comment by hluk** [comment]
@BjornMelgaard OK, I misunderstood your issue before.

CopyQ focuses previous window when item is selected from menu -- seems to work OK.

If you close the menu with ESC, CopyQ doesn't focus any windows but i3 focuses the window under mouse cursor. Same happens with other floating windows so it seems to be issue in i3 -- i.e. it should set focus to a different window under mouse cursor only if the cursor moves.

I don't think I can do anything about this.

**Comment by hluk** [comment]
@BjornMelgaard Actually there is this script you can use to launch the menu (requires `xdotool`).

```bash
# Store currently focused window
W=$(xdotool getactivewindow)
# Open the menu
xcopyq menu
# Wait for menu to close
W2=$(xdotool getactivewindow)
while [[ $W2 == $(xdotool getactivewindow) ]]; do sleep 0.1; done
# Activate last focused window
xdotool windowactivate $W
```

**Comment by BjornMelgaard** [comment]
```
#!/bin/sh
# Store currently focused window
W=$(xdotool getactivewindow)
echo $W
# Open the menu
copyq menu
# Wait for menu to close
W2=$(xdotool getactivewindow)
echo $W
while [[ $W2 == $(xdotool getactivewindow) ]]; do sleep 0.1; done
# Activate last focused window
xdotool windowactivate $W
```

```
 $ ./copyqmenu.sh
46137347
46137347
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
```
:smile: And I am not very good in shell script

**Comment by hluk** [comment]
Try to use `#!/bin/bash` instead.

**Comment by BjornMelgaard** [comment]
Tried, numbers are same, I will write to i3 tomorrow)

**Comment by hluk** [comment]
Perhaps `sleep 0.5` after the `copyq menu` would help.

**Comment by BjornMelgaard** [comment]
I have found alternative:

```
 bindsym $mod+p       exec --no-startup-id "copyq show"
 for_window [class="copyq"]             floating enable
```

And I have tried sleep))

**Comment by hluk** [comment]
@orschiro Is this still an issue with CopyQ 3.0.0?

**Comment by orschiro** [comment]
@hluk no, it has been resolved. Thank you so much for your responsive solutions. :-)

**Comment by hluk** [comment]
@orschiro No problem :)

**Comment by CyberShadow** [comment]
Moving from Arch Linux to NixOS, I encountered a strange new problem: the `copyq menu` i3 keybind sometimes caused the CopyQ menu to not get "focused" - still show up on the screen, but, any keyboard events still went to the previously focused window, with the only way to interact and dismiss the CopyQ menu being with the mouse.

> To bypass this you can add `--release` argument so the command is run after keys are relased.

This seems to fix the above problem reliably. Thank you!

**Comment by trapier** [comment]
For anyone wondering how to specify `--release` on an `xsession.windowManager.i3.config.keybindings` under nixos's home manager, this is the syntax:

```
  "--release mod4+c" = "exec --no-startup-id copyq menu";
```

courtesy of: https://github.com/nix-community/home-manager/issues/2071#issuecomment-854880469
