### ISSUE TITLE
Tab for URLs with Title and Icon not showing Icon

### ISSUE THREAD

**Issue by richlux** [hluk/CopyQ#773]
I'm using a CopyQ command from the repository to get the URL with Title and Icon (https://github.com/hluk/copyq-commands/blob/master/Automatic/tab-for-urls-with-title-and-icon.ini) and it gets the Title and the URL perfectly, but it nevers gets the Icon.  I have tried many many sites and the Icon never shows. Using the Show Content option, I see an "application/x-copyq-item-icon" entry, but it is always blank.  Any help would be appreciated.

Thanks,
Rich

**Comment by hluk** [comment]
I fixed the command, please re-add it to CopyQ.

**Comment by richlux** [comment]
Thanks, that fixed it. 

Rich

**Comment by richlux** [comment]
Have have two other issues with this command.  First, sometimes it still doesn't get an Icon. For example, it doesn't get an icon for http://www.woot.com or http://www.bgr.com.  Second, when it does get an Icon, there is always an extra grey square in front of it. Is there a way to remove the grey square?  See the attached screenshot for examples.

![image](https://user-images.githubusercontent.com/25157703/40081841-2d9cb428-585d-11e8-94c8-0c98a6eec9b3.png)

Rich

**Comment by hluk** [comment]
Can you please move this issue to [copyq-commands](https://github.com/hluk/copyq-commands/issues)? I also accept merge requests there.

Currently the favicon is retrieved from a HTML using [a naive regex](https://github.com/hluk/copyq-commands/blob/a7e591b9fcedddf8c3c3474084a866832a9e32e1/Automatic/tab-for-urls-with-title-and-icon.ini#L31). This often fails, or the icon is to small or not transparent.

Would be nice to use some proper way of retrieving favicons.
