### ISSUE TITLE
Item activation is messed up when in search mode

### ISSUE THREAD

**Issue by amosbird** [hluk/CopyQ#785]
I'm using Copyq master branch in archlinux.

1. search `fff` and select some item, ![](https://la.wentropy.com/FNXh.png)

2. press enter, ![](https://la.wentropy.com/2b-H.png)

it ends up with other text (here is `<C-w>`) which i have no idea where it comes from.

**Comment by hluk** [comment]
Isn't the pasted text same as the text of selected item? The screenshots suggest so.

**Comment by amosbird** [comment]
No, the selected (highlight) text is item `578`. The first item is a previous result of reproducing this bug.

**Comment by hluk** [comment]
Oh, OK, I didn't notice the selection color in the first screenshot.

It's possible that the new clipboard content haven't yet propagated to target application. Can you reproduce it when pasting to different apps?

See also #562.

**Comment by amosbird** [comment]
yeah, it's reproducable everywhere.

**Comment by hluk** [comment]
Does the clipboard at least contain the correct text after activating an item?

**Comment by amosbird** [comment]
yes, with garbage text appending to it.

**Comment by hluk** [comment]
Do you use Enter key to activate the items? Is there any custom command assigned to Enter/Return shortcut?

**Comment by amosbird** [comment]
yeah i use `enter` to activate.  ![](https://la.wentropy.com/uW1Z.png)  i don't see any command assigned with `enter`

**Comment by hluk** [comment]
No idea why the text is added. Is there any other app that could automatically modify the clipboard?

Does this happen also when not searching?

**Comment by amosbird** [comment]
No, it only happens when searching.

> Is there any other app that could automatically modify the clipboard?

not that I'm aware of.

**Comment by amosbird** [comment]
Um, can I manually setup a `Enter` command to paste text? I think that may work around this problem.

**Comment by hluk** [comment]
Yes, overriding item activation action is mentioned in the issue #562.

```ini
[Command]
Command="
    copyq:
    var text = input()
    copy(text)
    copySelection(text)
    paste()
    filter() // clear search"
HideWindow=true
Icon=\xf0ea
InMenu=true
Input=text/plain
Name=Paste Selected Items
Shortcut=enter
```

**Comment by amosbird** [comment]
well, it doesn't work....

**Comment by amosbird** [comment]
well, it doesn't work....

**Comment by hluk** [comment]
Does it at least focus the target window after you select item and press Enter?

**Comment by amosbird** [comment]
well, it behaves exactly the same as the builtin `enter`, generating addtional garbage text when pasting in search mode.

**Comment by hluk** [comment]
What window manager do you use?

**Comment by amosbird** [comment]
i3wm

**Comment by hluk** [comment]
I'm testing i3 and emacs but cannot reproduce this issue.

Can you try updating CopyQ? I've pushed a lot of fixes today to master branch.

**Comment by amosbird** [comment]
I've updated to CopyQ Clipboard Manager v3.0.3-89-gae63eb82 (hluk@email.cz). This issue still exists.

**Comment by amosbird** [comment]
Hmm, this doesn't always happen for any items. And the appending text varies.

**Comment by hluk** [comment]
Is a new item with the appended text added to the list in CopyQ? This would suggest that some external application changed the clipboard again.

**Comment by amosbird** [comment]
no, copyq list remains unchanged

**Comment by hluk** [comment]
Can you share your configuration? (`~/.config/copyq/copyq.conf`)

**Comment by amosbird** [comment]
https://la.wentropy.com/paj8

**Comment by hluk** [comment]
Hmm, no luck with your config. How do you open main window?

**Comment by amosbird** [comment]
using `copyq toggle`

**Comment by hluk** [comment]
Do you have the shortcut defined in i3 configuration? Can you share the config line?

**Comment by amosbird** [comment]
I use `sxhkd` to set up the key bindings.
```
mod3+f
  copyq toggle
```

**Comment by amosbird** [comment]
would it be possible that this issue is due to large number of copyq items (9999 in my case) ?

**Comment by hluk** [comment]
Having lots of items doesn't seem to have any effect.

...I'm starting to get out of ideas.

What other texts are appended? Is there an item with the `<C-w>` text anywhere?

**Comment by amosbird** [comment]
lemme do a screencast to show the maybe-patterns i've found.

**Comment by amosbird** [comment]
https://la.wentropy.com/TN-f.webm

**Comment by hluk** [comment]
Nice, thanks for the screencast.

The command that selects next/previous item doesn't work well when some items are filtered-out. I'll try to fix it later.

**Comment by hluk** [comment]
This should be fixed now.

**Comment by amosbird** [comment]
Thanks. I just did some tests and it works fine now.
