### ISSUE TITLE
"Process crashed" popup and log entries

### ISSUE THREAD

**Issue by richtrefz** [hluk/CopyQ#881]
![screenshot-20180220-15-23-14](https://user-images.githubusercontent.com/1500959/36447640-f379d2ea-1652-11e8-81cd-6a252d80ceea.png)

CopyQ v3.2.0 running on Linux Mint

Not sure what the pattern is.  As you can see it happens every 3 days or so. 

```
Note [2018-02-14 17:58:38.280] Server-4567: Command “copyq provideSelection”
Note [2018-02-14 17:58:38.280] Server-4567:    Error: Process crashed
Note [2018-02-14 17:58:38.280] Server-4567:    1. copyq provideSelection
Note [2018-02-17 16:28:27.507] Server-28116: Command “copyq provideSelection”
Note [2018-02-17 16:28:27.507] Server-28116:    Error: Process crashed
Note [2018-02-17 16:28:27.507] Server-28116:    1. copyq provideSelection
Note [2018-02-17 16:28:27.575] Server-28116: Command “copyq provideClipboard”
Note [2018-02-17 16:28:27.575] Server-28116:    Error: Process crashed
Note [2018-02-17 16:28:27.575] Server-28116:    1. copyq provideClipboard
Note [2018-02-20 15:22:51.016] Server-28373: Command “copyq provideSelection”
Note [2018-02-20 15:22:51.016] Server-28373:    Error: Process crashed
Note [2018-02-20 15:22:51.016] Server-28373:    1. copyq provideSelection
```

**Comment by hluk** [comment]
Interesting. Are you using X11 or Wayland?

**Comment by richtrefz** [comment]
> loginctl show-session c1 -p Type 
Type=x11

**Comment by richtrefz** [comment]
Seems like its not going away :-) 
If there is anything I can do to help figure out what is going on - please ask
```
Note [2018-02-22 11:35:00.715] Server-1774: Command “copyq provideSelection”
Note [2018-02-22 11:35:00.715] Server-1774:    Error: Process crashed
Note [2018-02-22 11:35:00.715] Server-1774:    1. copyq provideSelection
Note [2018-02-22 11:35:00.864] Server-1774: Command “copyq provideClipboard”
Note [2018-02-22 11:35:00.864] Server-1774:    Error: Process crashed
Note [2018-02-22 11:35:00.864] Server-1774:    1. copyq provideClipboard
Note [2018-02-22 16:32:06.930] Server-1774: Command “copyq provideClipboard”
Note [2018-02-22 16:32:06.930] Server-1774:    Error: Process crashed
Note [2018-02-22 16:32:06.930] Server-1774:    1. copyq provideClipboard
```

**Comment by hluk** [comment]
Can you provide output of following commands?

```bash
copyq --version
coredumpctl dump --reverse copyq
ldd "$(which copyq)"
```

**Comment by richtrefz** [comment]
```
> copyq --version
CopyQ Clipboard Manager v3.2.0 (hluk@email.cz)
Built with: Qt 5.5.1, LibQxt 0.7.0

> ldd "$(which copyq)"
	linux-vdso.so.1 =>  (0x00007ffc1b379000)
	/nixshared/active-profile/bin/libstderred.so (0x00007f70eadfb000)
	libQt5Network.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00007f70eb092000)
	libQt5Script.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Script.so.5 (0x00007f70eab73000)
	libXtst.so.6 => /usr/lib/x86_64-linux-gnu/libXtst.so.6 (0x00007f70ea96d000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f70ea633000)
	libQt5Widgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (0x00007f70e9fa6000)
	libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007f70e9a5e000)
	libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007f70e9588000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f70e9206000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f70e8efd000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f70e8ce7000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f70e891d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f70eb000000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f70e8719000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f70e84fc000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f70e82e2000)
	libproxy.so.1 => /usr/lib/x86_64-linux-gnu/libproxy.so.1 (0x00007f70e80c1000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f70e7eaf000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f70e7c8d000)
	libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f70e7a3a000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f70e7729000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007f70e7504000)
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f70e72a6000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 (0x00007f70e7033000)
	libicui18n.so.55 => /usr/lib/x86_64-linux-gnu/libicui18n.so.55 (0x00007f70e6bd1000)
	libicuuc.so.55 => /usr/lib/x86_64-linux-gnu/libicuuc.so.55 (0x00007f70e683d000)
	libpcre16.so.3 => /usr/lib/x86_64-linux-gnu/libpcre16.so.3 (0x00007f70e65d7000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f70e63cf000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f70e61cb000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f70e5fc5000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f70e5dbd000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f70e5b4d000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f70e58a3000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f70e567d000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f70e5454000)
	libxcb-dri3.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0 (0x00007f70e5251000)
	libxcb-present.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-present.so.0 (0x00007f70e504e000)
	libxcb-sync.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007f70e4e47000)
	libxshmfence.so.1 => /usr/lib/x86_64-linux-gnu/libxshmfence.so.1 (0x00007f70e4c44000)
	libglapi.so.0 => /usr/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007f70e4a14000)
	libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007f70e4811000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f70e460b000)
	libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007f70e4409000)
	libxcb-glx.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0 (0x00007f70e41f0000)
	libxcb-dri2.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0 (0x00007f70e3feb000)
	libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007f70e3de5000)
	libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007f70e3bd4000)
	libicudata.so.55 => /usr/lib/x86_64-linux-gnu/libicudata.so.55 (0x00007f70e211d000)
```

Maybe need to wait until it happens again?
```
> coredumpctl 
No coredumps found.
```
Also
```
> coredumpctl dump --reverse copyq
coredumpctl: unrecognized option '--reverse'
```

**Comment by richtrefz** [comment]
Did you want to look at the /var/lib/systemd/coredump/core.copyq.1000.* files it made? They are about 600K compressed
```
> coredumpctl info copyq
           PID: 11714 (copyq)
           UID: 1000 (rich)
           GID: 1000 (rich)
        Signal: 11 (SEGV)
     Timestamp: Sat 2018-02-24 17:58:32 EST (8min ago)
  Command Line: /nixshared/twd-lmxfce-201801/opt/bin/copyq provideSelection
    Executable: /nixshared/twd-lmxfce-201801/opt/bin/copyq
 Control Group: /
         Slice: -.slice
       Boot ID: dc7d09fbd22e4d22b6e5c0d68d7d09e8
    Machine ID: 0a2058fc54c649ada1c67c1b7f870152
      Hostname: twd-lmxfce-201801
      Coredump: /var/lib/systemd/coredump/core.copyq.1000.dc7d09fbd22e4d22b6e5c0d68d7d09e8.11714.1519513112000000000000.xz
       Message: Process 11714 (copyq) of user 1000 dumped core.
                
                Stack trace of thread 11715:
                #0  0x00007f5a2572c889 n/a (n/a)

           PID: 11706 (copyq)
           UID: 1000 (rich)
           GID: 1000 (rich)
        Signal: 11 (SEGV)
     Timestamp: Sat 2018-02-24 17:58:37 EST (8min ago)
  Command Line: /nixshared/twd-lmxfce-201801/opt/bin/copyq provideClipboard
    Executable: /nixshared/twd-lmxfce-201801/opt/bin/copyq
 Control Group: /
         Slice: -.slice
       Boot ID: dc7d09fbd22e4d22b6e5c0d68d7d09e8
    Machine ID: 0a2058fc54c649ada1c67c1b7f870152
      Hostname: twd-lmxfce-201801
      Coredump: /var/lib/systemd/coredump/core.copyq.1000.dc7d09fbd22e4d22b6e5c0d68d7d09e8.11706.1519513117000000000000.xz
       Message: Process 11706 (copyq) of user 1000 dumped core.
                
                Stack trace of thread 11707:
                #0  0x00007f4ae04d0889 n/a (n/a)
```

**Comment by hluk** [comment]
I cannot reproduce this issue. I suspect that your version of app was build with different libraries than are currently installed on your system. This also happened to me on an partially updated system (perhaps Qt used some incompatible libraries), so updating all installed packages can help.

Where did you get CopyQ from?

**Comment by richtrefz** [comment]
I downloaded https://github.com/hluk/CopyQ/archive/v3.2.0.tar.gz and basically do
```
cmake -Wno-dev  -DWITH_QT5=TRUE 
make
sudo make install
```

**Comment by hluk** [comment]
If you upgraded system packages, you may need to rebuild the app.

**Comment by richtrefz** [comment]
I compiled it very recently.  I may drop back a version - I think this started with 3.2

Linux Mint is based on Ubuntu 16 which is based on Debian 9, so I guess copyq_3.2.0_Debian_9.0-1_amd64.deb should work.  Might be worth trying a pre-built version.

I appreciate that you spent time looking at this.

**Comment by ipleten** [comment]
I have the same problem on Ubuntu Ubuntu 16.04.3 LTS with all updates applied:
![image](https://user-images.githubusercontent.com/6207156/36724888-3d1413c4-1bbd-11e8-86a7-c6e011f0ccd5.png)

>  tamerlan@IF170:~$ copyq --version
CopyQ Clipboard Manager v3.2.0 (hluk@email.cz)
Built with: Qt 5.5.1, LibQxt 0.7.0

>tamerlan@IF170:~$ ldd "$(which copyq)"
	linux-vdso.so.1 =>  (0x00007ffcaf8ff000)
	libQt5Network.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00007f63bc813000)
	libQt5Script.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Script.so.5 (0x00007f63bbfec000)
	libXtst.so.6 => /usr/lib/x86_64-linux-gnu/libXtst.so.6 (0x00007f63bbde6000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f63bbaac000)
	libQt5Widgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (0x00007f63bb41f000)
	libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007f63baed7000)
	libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007f63baa01000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f63ba67f000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f63ba376000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f63ba160000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f63b9d96000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f63bc776000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f63b9b79000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f63b995f000)
	libproxy.so.1 => /usr/lib/x86_64-linux-gnu/libproxy.so.1 (0x00007f63b973e000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f63b952c000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f63b930a000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f63b9106000)
	libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f63b8eb3000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f63b8ba2000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007f63b897d000)
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f63b871f000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 (0x00007f63b84ac000)
	libicui18n.so.55 => /usr/lib/x86_64-linux-gnu/libicui18n.so.55 (0x00007f63b804a000)
	libicuuc.so.55 => /usr/lib/x86_64-linux-gnu/libicuuc.so.55 (0x00007f63b7cb6000)
	libpcre16.so.3 => /usr/lib/x86_64-linux-gnu/libpcre16.so.3 (0x00007f63b7a50000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f63b7848000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f63b7644000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f63b743e000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f63b7236000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f63b6fc6000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f63b6d1c000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f63b6af6000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f63b68cd000)
	libxcb-dri3.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0 (0x00007f63b66ca000)
	libxcb-present.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-present.so.0 (0x00007f63b64c7000)
	libxcb-sync.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007f63b62c0000)
	libxshmfence.so.1 => /usr/lib/x86_64-linux-gnu/libxshmfence.so.1 (0x00007f63b60bd000)
	libglapi.so.0 => /usr/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007f63b5e8d000)
	libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007f63b5c8a000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f63b5a84000)
	libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007f63b5882000)
	libxcb-glx.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0 (0x00007f63b5669000)
	libxcb-dri2.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0 (0x00007f63b5464000)
	libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007f63b525e000)
	libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007f63b504d000)
	libicudata.so.55 => /usr/lib/x86_64-linux-gnu/libicudata.so.55 (0x00007f63b3596000)`

**Comment by hluk** [comment]
Maybe it's some bug in Qt 5.5.1 -- possibly fixed with 41d1d623d6691c23494c57c699f77706ba2f346a.

**Comment by richtrefz** [comment]
seems to still occur.  the weird thing is: 2 messages popped up -- but I hadn't used the clipboard for a couple of minutes before that
```
coredumpctl info copyq
           PID: 14581 (copyq)
           UID: 1000 (rich)
           GID: 1000 (rich)
        Signal: 11 (SEGV)
     Timestamp: Mon 2018-03-05 15:31:52 EST (7min ago)
  Command Line: /opt/bin/copyq provideSelection
    Executable: /opt/bin/copyq
 Control Group: /
         Slice: -.slice
       Boot ID: a6c8907cd439473484203d8a874b9340
    Machine ID: 0a2058fc54c649ada1c67c1b7f870152
      Hostname: twd-lmxfce-201801
      Coredump: /var/lib/systemd/coredump/core.copyq.1000.a6c8907cd439473484203d8a874b9340.14581.1520281912000000000000.xz
       Message: Process 14581 (copyq) of user 1000 dumped core.
                
                Stack trace of thread 14582:
                #0  0x00007f876d7e2889 n/a (n/a)
```

**Comment by pehlm** [comment]
Same for me on Ubuntu 16.04.4. All Ubuntu stock dependency packages and your CopyQ package on ppa:hluk/copyq. Began today. Not earlier and I'm using CopyQ very often.

**Comment by richtrefz** [comment]
In case I never said it, for me this began with v3.2.0.  I've been using 3.0.3 recently and never see this problem.

**Comment by hluk** [comment]
> In case I never said it, for me this began with v3.2.0. I've been using 3.0.3 recently and never see this problem.

The clipboard is provided in separate process in the new version. The problem could be that the process can be still running even though clipboard is already provided by different process. I have fixed for this, but it will be available in next version (v3.2.1).

It would help, if someone can build and test this with debug symbols (`-DCMAKE_BUILD_TYPE=Debug` cmake flag). This should reveal the stack trace with `coredumpctl info copyq` if the process crashes again.

**Comment by hluk** [comment]
If anyone wants to try beta version with the fix, you can use [copyq-beta PPA](https://launchpad.net/~hluk/+archive/ubuntu/copyq-beta).

**Comment by richtrefz** [comment]
I complied that beta on 3/9, no problems so far

**Comment by richtrefz** [comment]
Still no joy with the copyq-beta PPA.
```
           PID: 24328 (copyq)
           UID: 1000 (rich)
           GID: 1000 (rich)
        Signal: 11 (SEGV)
     Timestamp: Thu 2018-03-15 14:52:54 EDT (6min ago)
  Command Line: /opt/bin/copyq provideSelection
    Executable: /opt/bin/copyq
 Control Group: /
         Slice: -.slice
       Boot ID: dcb27f61afae494e8998c7a5f267a6e3
    Machine ID: 0a2058fc54c649ada1c67c1b7f870152
      Hostname: twd-lmxfce-201801
      Coredump: /var/lib/systemd/coredump/core.copyq.1000.dcb27f61afae494e8998c7a5f267a6e3.24328.1521139974000000000000.xz
       Message: Process 24328 (copyq) of user 1000 dumped core.
                
                Stack trace of thread 24329:
                #0  0x00007f6b25ee2889 n/a (n/a)

           PID: 24325 (copyq)
           UID: 1000 (rich)
           GID: 1000 (rich)
        Signal: 11 (SEGV)
     Timestamp: Thu 2018-03-15 14:52:54 EDT (6min ago)
  Command Line: /opt/bin/copyq provideClipboard
    Executable: /opt/bin/copyq
 Control Group: /
         Slice: -.slice
       Boot ID: dcb27f61afae494e8998c7a5f267a6e3
    Machine ID: 0a2058fc54c649ada1c67c1b7f870152
      Hostname: twd-lmxfce-201801
      Coredump: /var/lib/systemd/coredump/core.copyq.1000.dcb27f61afae494e8998c7a5f267a6e3.24325.1521139974000000000000.xz
       Message: Process 24325 (copyq) of user 1000 dumped core.
                
                Stack trace of thread 24326:
                #0  0x00007f1dc0310889 n/a (n/a)
```

**Comment by morsedl** [comment]
+1

```
morse@d117237 ~> lsb_release -a
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:printing-9.20160110ubuntu0.2-amd64:printing-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```

**Comment by hluk** [comment]
Is this still an issue with CopyQ v3.5.0?

**Comment by richtrefz** [comment]
Since the original post, I've moved to a Ubuntu 18 derivative so Qt is now 5.9.5, kernel is 4.15, etc.  So I don't know what to give credit to, but it has been rock solid.  No problems at all.

Thank you for checking.

**Comment by ipleten** [comment]
I'm on Ubuntu 16.04.05 it works well. Thank you.

**Comment by Luke-SF** [comment]
I'm on Ubuntu 18.04 and it started breaking today.

**Comment by Muzietto** [comment]
I'm on Ubuntu 18.04 and it started breaking yesterday.
