### ISSUE TITLE
CopyQ error messages on Windows exit

### ISSUE THREAD

**Issue by Mantukai** [hluk/CopyQ#902]
I am trying your software and find it quite useful.   I have some abnormal behavior – on Windows shutdown CopyQ shoots numerous error messages above the notification area.  You can see that on the screenshot.  Perhaps you could address this when time allows?
Windows 7 SP1 64-bit
CopyQ ver. 3.2.0

![image](https://user-images.githubusercontent.com/28905723/37565644-606ed4e0-2ac6-11e8-860b-9f6d81683bc7.png)

**Comment by hluk** [comment]
This is probably fixed in [v3.4.0](https://github.com/hluk/CopyQ/releases/tag/v3.4.0). Can you verify?

**Comment by Mantukai** [comment]
Hi,  I see that you already closed the ticket.  The problem became smaller in size – now instead of a bunch of bubbles I have only 2 or 3 when laptop is shutting down.  But they are still showing.

**Comment by hluk** [comment]
OK, I'm reopening this (I was really confident it's fixed).

The big amount of notifications is different issue that was fixed in last version.

BTW, is this blocking the shutdown?

**Comment by Mantukai** [comment]
No, shut down happens normally, only your app throws a few bubbles.

**Comment by hluk** [comment]
I managed to reproduce the issue, but it's really hard to debug since I must basically sign out of the system to test this.

Looks like system is killing the clipboard monitor process somehow - it exits with 1073807364 - maybe it's bug in Qt. Not sure how to fix this - currently I can only prevent the notification for such exit codes.

**Comment by Mantukai** [comment]
Thanks for trying.  Don’t spend anymore time on this.  Even though the error messages are generated on exit the data is not lost.  I can live with this.

Actually yesterday I closed all foreground applications including all those in the tray before shutting down.  I left only CopyQ running.  When I shut the laptop down CopyQ exited without any bubbles.  So, what happens on my machine may be a conflict with some very specific application.
